apiVersion: v1
kind: Pod
metadata:
  name: mongo
  labels: 
    app: mongo
spec:
  containers:
    - name: mongo
      image: mongo:latest
      ports:
      - containerPort: 27017
      volumeMounts:
        - mountPath: "/data/db"
          name: mongo
  volumes:
    - name: mongo
      persistentVolumeClaim:
        claimName: mongo
