version: '3.7'

volumes:
  mongo:
  nginx:

services:
  mongo:
    image: mongo:latest
    volumes:
    - type: volume
      source: mongo
      target: /data/db
    ports:
    - target: 27017
      published: 27017
      protocol: tcp
 
  backend:
    image: backend:latest
    build: ./TeamAPoolProjectBackend
    ports:
    - target: 8080
      published: 8080
      protocol: tcp
    depends_on:
    - mongo

  frontend:
    image: frontend:latest
    build: ./TeamAPoolProjectUI
    ports:
    - target: 4200
      published: 4200
      protocol: tcp
    depends_on:
    - backend
    - mongo

  nginx:
    image: nginx:latest
    volumes:
    - type: bind
      source: ./TeamAPoolProjectUI/nginx.conf
      target: /etc/nginx/nginx.conf
    ports:
    - target: 80
      published: 80
      protocol: tcp
    depends_on:
    - frontend
    - backend
    - mongo
